name: Register Container App

on:
  workflow_dispatch:
    inputs:

      spoke_name:
        description: Spoke Name
        required: true
        type: string

      container_app_fqdn:
        description: Container App FQDN
        required: true
        type: string

permissions:
  id-token: write
  contents: write

jobs:

  register:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Update Registry
        shell: bash
        run: |

          SPOKE="${{ github.event.inputs.spoke_name }}"
          FQDN="${{ github.event.inputs.container_fqdn }}"

          if [ ! -f applications.json ]; then
            echo '{}' > applications.json
          fi

          jq \
            --arg spoke "$SPOKE" \
            --arg fqdn "$FQDN" \
            '. + {
                ($spoke): {
                  type: "containerapp",
                  fqdn: $fqdn
                }
              }' \
            applications.json > tmp.json

          mv tmp.json applications.json
          
      - name: Register Container App
        shell: bash
        run: |

          retry() {
              local max=5
              local delay=15
              local attempt=1

              while true; do

              "$@" && return 0

              if [ "$attempt" -ge "$max" ]; then
                echo "FAILED after $max attempts"
                return 1
              fi

              echo "Retry $attempt/$max"
              attempt=$((attempt + 1))

              sleep $delay

              done
            }

            SPOKE=$(echo "${{ github.event.inputs.spoke_name }}" | tr '[:upper:]' '[:lower:]')

            TARGET="${{ github.event.inputs.container_app_fqdn }}"
            
            TARGET=$(echo "$TARGET" \
              | sed 's|^https://||' \
              | sed 's|^http://||' \
              | sed 's|/$||')

            echo "Registering:"
            echo "${SPOKE}.dar.internal"
            echo " -> ${TARGET}"

           retry az network private-dns record-set cname create \
              --resource-group RG-Hub-SBX \
              --zone-name dar.internal \
              --name "$SPOKE" \
              --if-none-match

           retry az network private-dns record-set cname set-record \
              --resource-group RG-Hub-SBX \
              --zone-name dar.internal \
              --record-set-name "$SPOKE" \
              --cname "$TARGET"

           retry az network application-gateway address-pool update \
              --gateway-name agw-sbx \
              --resource-group RG-Hub-SBX \
              --name "${SPOKE}-pool" \
              --servers "$TARGET"
              
      - name: Commit Registry
        run: |

          git config user.name github-actions
          git config user.email github-actions@github.com

          git add applications.json

          git commit -m "Register application for ${{ github.event.inputs.spoke_name }}" || exit 0

          git push
