name: Create Spoke
on:
  workflow_dispatch:
    inputs:
      spoke_name:
        description: Spoke name
        required: true
        type: string
      keepalive:
        description: Spoke Persistence
        required: false
        default: "false"
        type: string
permissions:
  id-token: write
  contents: write
jobs:
  create-spoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Allocate spoke Index
        shell: bash
        run: |
          spoke="${{ github.event.inputs.spoke_name }}"
          if [ ! -f spokes.json ]; then
            echo '{}' > spokes.json
          fi
          if jq -e --arg t "$spoke" '.[$t]' spokes.json > /dev/null; then
            echo "spoke already exists"
            exit 1
          fi
          NEXT=$(jq '
          [.[]] as $used
          | first(
              range(1;1025)
              | select(. as $i | ($used | index($i)) | not)
            )
          ' spokes.json)
          jq \
            --arg spoke "$spoke" \
            --argjson idx "$NEXT" \
            '. + {($spoke): $idx}' \
            spokes.json > tmp.json
          mv tmp.json spokes.json
          cat spokes.json
          cat > terraform.auto.tfvars.json <<EOF
          {
            "spoke_name": "$spoke",
            "spoke_index": $NEXT,
            "keepAlive":  "${{ github.event.inputs.keepalive }}"
          }
          EOF
          echo "Allocated spoke index: $NEXT"
      - name: Show tfvars
        run: |
          cat terraform.auto.tfvars.json
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan
        run: terraform plan
      - name: Terraform Apply
        run: terraform apply -auto-approve
      - name: Commit Allocation Registry
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add spokes.json
          git commit -m "Add spoke ${{ github.event.inputs.spoke_name }}" || exit 0
          git push
